# Generated by Django 3.1.2 on 2020-10-04 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=40)),
                ('hackathons', models.IntegerField()),
                ('progLanguages', models.TextField()),
                ('databases', models.TextField()),
                ('interests', models.TextField()),
                ('latest', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'UserProfiles',
            },
        ),
    ]
